apiVersion: incidentary.incidentary.com/v1alpha1
kind: IncidentaryConfig
metadata:
  labels:
    app.kubernetes.io/name: incidentary-operator
    app.kubernetes.io/managed-by: kustomize
  name: incidentaryconfig-sample
spec:
  # TODO(user): Add fields here
