apiVersion: v1
kind: Service
metadata:
  name: {{ include "incidentary-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "incidentary-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: health
      port: 8081
      targetPort: health
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "incidentary-operator.selectorLabels" . | nindent 4 }}
